-- FinLens — Phase 2: extend the existing `events` table with what
-- ingestion needs (stable external id for dedup, category, raw payload),
-- and add the two tables Phase 3 (real Agenda data) depends on.
-- Safe to re-run: every statement is idempotent.

-- 1. Extend the existing events table -----------------------------------
alter table public.events
  add column if not exists external_id text,
  add column if not exists category text,
  add column if not exists raw_data jsonb;

create unique index if not exists events_external_id_key
  on public.events (external_id)
  where external_id is not null;

-- 2. stocks — one row per ticker we've ever seen referenced -------------
create table if not exists public.stocks (
  id bigint generated by default as identity primary key,
  ticker text not null unique,
  company_name text,
  exchange text,
  sector text,
  industry text,
  country text,
  currency text,
  logo_url text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

alter table public.stocks enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'stocks' and policyname = 'Public read access'
  ) then
    create policy "Public read access" on public.stocks for select using (true);
  end if;
end $$;

-- 3. ingestion_runs — operational log for each sync job ------------------
-- No public policy on purpose: only the service-role key (used by sync
-- jobs, server-side only) can read/write this table.
create table if not exists public.ingestion_runs (
  id bigint generated by default as identity primary key,
  provider text not null,
  job_type text not null,
  started_at timestamp with time zone not null default now(),
  completed_at timestamp with time zone,
  status text not null default 'running',
  items_received integer not null default 0,
  items_created integer not null default 0,
  items_updated integer not null default 0,
  items_skipped integer not null default 0,
  items_failed integer not null default 0,
  error_message text
);

alter table public.ingestion_runs enable row level security;
