-- Real news articles, ingested from Finnhub and analyzed by OpenAI.
create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  external_id text unique,
  title text not null,
  summary text,
  url text,
  source_name text,
  author text,
  published_at timestamp with time zone not null,
  image_url text,
  tickers text[] not null default '{}',

  -- Filled in by OpenAI analysis:
  category text,
  impact_score smallint check (impact_score is null or (impact_score >= 1 and impact_score <= 10)),
  impact_direction text,
  what_happened text,
  why_it_matters text,
  market_impact text,
  what_to_watch text[] not null default '{}',

  raw_data jsonb,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

alter table public.articles enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'articles' and policyname = 'Public read access'
  ) then
    create policy "Public read access" on public.articles for select using (true);
  end if;
end $$;
