-- Stock price reaction snapshots, captured at ingestion time for articles
-- the AI flags as a major company-specific event. Never fabricated: a row
-- only exists if we actually fetched a real quote at capture time.
alter table public.articles
  add column if not exists company_event_type text;

create table if not exists public.article_price_reactions (
  id bigint generated by default as identity primary key,
  article_id bigint not null references public.articles(id) on delete cascade,
  ticker text not null,
  index_ticker text not null default 'SPY',
  price_at_announcement numeric,
  index_price_at_announcement numeric,
  captured_at timestamp with time zone not null default now(),
  unique (article_id, ticker)
);

alter table public.article_price_reactions enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'article_price_reactions'
      and policyname = 'Public read access'
  ) then
    create policy "Public read access" on public.article_price_reactions
      for select using (true);
  end if;
end $$;
