-- Per-ticker directional signals ("catalysts") extracted from an article,
-- plus the follow-up prices used to measure FinLens's own track record.
--
-- A signal is the AI's assessment that a piece of news is good or bad for a
-- specific company — never a price prediction. Every signal is kept, right
-- or wrong, so the published hit rate is honest.
--
-- Safe to run more than once. Requires 0004_articles.sql.

create table if not exists public.article_signals (
  id bigint generated by default as identity primary key,
  article_id bigint not null references public.articles(id) on delete cascade,
  ticker text not null,

  -- The assessment
  direction text not null check (direction in ('positive', 'negative')),
  confidence text not null check (confidence in ('high', 'medium', 'low')),
  horizon text not null check (horizon in ('short', 'long')),
  -- 'direct': the company is named in the article and a quoted sentence
  --           supports the link.
  -- 'chain':  a second-order effect (supplier, customer, competitor).
  link_level text not null check (link_level in ('direct', 'chain')),
  rationale text not null,
  -- Sentence copied from the article that supports the signal. Checked in
  -- code to actually appear in the source text before being stored.
  evidence_quote text not null,
  -- True when the second AI pass confirmed the link.
  verified boolean not null default false,

  -- Baseline captured when the signal was created (null if no real quote
  -- was available — such a signal is never counted in the track record).
  index_ticker text not null default 'SPY',
  price_at_signal numeric,
  index_price_at_signal numeric,

  -- Follow-up snapshots filled by /api/cron/track-signals.
  price_1d numeric,
  index_price_1d numeric,
  checked_1d_at timestamp with time zone,
  price_1w numeric,
  index_price_1w numeric,
  checked_1w_at timestamp with time zone,
  price_1m numeric,
  index_price_1m numeric,
  checked_1m_at timestamp with time zone,

  created_at timestamp with time zone not null default now(),
  unique (article_id, ticker)
);

create index if not exists article_signals_article_id_idx
  on public.article_signals (article_id);
create index if not exists article_signals_created_at_idx
  on public.article_signals (created_at);

alter table public.article_signals enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'article_signals'
      and policyname = 'Public read access'
  ) then
    create policy "Public read access" on public.article_signals
      for select using (true);
  end if;
end $$;
