-- Push notifications and the morning brief.
-- Safe to run more than once. Requires 0008_accounts_subscriptions.sql.

-- One row per device/browser that allowed notifications.
create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique check (endpoint like 'https://%'),
  p256dh text not null,
  auth text not null,
  user_agent text,
  created_at timestamptz not null default now(),
  last_used_at timestamptz
);
create index if not exists push_subscriptions_user_idx on public.push_subscriptions (user_id);

alter table public.push_subscriptions enable row level security;
do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'push_subscriptions' and policyname = 'push_owner') then
    create policy push_owner on public.push_subscriptions for all to authenticated
      using ((select auth.uid()) = user_id)
      with check ((select auth.uid()) = user_id);
  end if;
end $$;
grant select, insert, update, delete on public.push_subscriptions to authenticated;

-- Notification preferences and the user's time zone (for the 8 a.m. brief).
alter table public.profiles add column if not exists notify_signals boolean not null default true;
alter table public.profiles add column if not exists notify_morning boolean not null default true;
alter table public.profiles add column if not exists timezone text;
alter table public.profiles add column if not exists last_morning_push date;

-- Morning brief: every hour; the route only sends to people for whom it is
-- 8 a.m. on a weekday (see src/app/api/cron/morning-brief). Requires 0009.
select cron.schedule('finlens-morning-brief', '3 * * * *',
  $$select public.call_finlens_job('/api/cron/morning-brief')$$);
